name: Docker

on:
  release:
    types: [ published ]
  push:
    branches:
      - master

jobs:
  push_to_registries:
    name: Publish Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Docker tag
        id: prep
        run: |
          VERSION=noop
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=latest
            fi
          fi
          echo ::set-output name=tags::${VERSION}

      - name: Clone
        uses: actions/checkout@v2

      - name: Build and publish to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          repository: ledgerhq/bitcoin-lib-grpc/bitcoin-lib-grpc
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.prep.outputs.tags }}
          push: true
